modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/HttpRafa/Universe-Matter/issues"
license = "MIT"

[[mods]]
modId = "universe_matter"
version = "${version}"
displayName = "Universe Matter"
authors = "HttpRafa"
description = '''
Allows the use of energy from the universe. BUT BE CAREFUL!
'''
logoFile = "icon.png"

[[dependencies.universe_matter]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.universe_matter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.universe_matter]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"
